.TH UPDATE-CERTDATA "8" "December 2022" "update-certdata 0.3" "System Administration Utilities"
.SH NAME
update-certdata \- manual page for update-certdata 0.3
.SH DESCRIPTION
update\-certdata will check the existng local version of
certdata.txt against the version in Mozzila's HG instance for NSS, and if
necessary, download and install an updated version. It will then proceed to
populate the P11\-kit trust anchors using Mozilla's trust arguments.
Additionally, if any p11\-kit format files are in place in the local directory,
they will overwrite those taken from the Mozilla store.
.PP
Example: update\-certdata
