.TH UPDATE-CCADB "8" "December 2022" "update-ccadb 0.3" "System Administration Utilities"
.SH NAME
update-ccadb \- manual page for update-ccadb 0.3
.SH DESCRIPTION
update\-ccadb will download the latest version of certificate
bundles from the Common CA Database managed by Mozilla, Microsoft, and Google.
It will then proceed to populate the P11\-kit trust anchors using the trust
values for the bundles downloaded. Additionally, if any p11\-kit format files
are in place in the local directory, they will overwrite those taken from the
CCADB bundles.
.PP
Example: update\-ccadb
